# Generated by Django 6.0.7 on 2026-10-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_register_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('Country', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=250)),
                ('images', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
    ]
